name: AppImage Build
on: push

jobs:

  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-22.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      # Runs a set of commands using the runners shell
      - name: Download building tools & executing AppImage build
        run: |
          sudo apt install fuse
          wget -O appimage-builder-x86_64.AppImage https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage
          chmod +x appimage-builder-x86_64.AppImage
          ./appimage-builder-x86_64.AppImage
          mv lol-for-linux-installer*.AppImage lol-for-linux-installer.AppImage
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lol-for-linux-installer
          path: "./lol-for-linux-installer.AppImage"
        
